field: 385ea997-6d59-4816-a529-29d66a8c43b8 # Log Blocks
fieldLayouts:
  a2786c67-efe1-46a3-97de-ecc670ccc96a:
    tabs:
      -
        elements:
          -
            fieldUid: e5c502b2-96a0-40e8-906e-90865c246d78 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 26b3cb3e-26b5-4a51-895f-09ac38ddd2f5 # Image Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: dd581b2f-56b7-4559-b893-329b66618f29 # Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 24d54bcc-c58c-43d8-b3e0-501f1e9301d3 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  24d54bcc-c58c-43d8-b3e0-501f1e9301d3: # Caption
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  26b3cb3e-26b5-4a51-895f-09ac38ddd2f5: # Image Width
    contentColumnType: text
    fieldGroup: null
    handle: imageWidth
    instructions: ''
    name: 'Image Width'
    searchable: false
    settings:
      displayAsGraphic: '1'
      displayFullwidth: ''
      options:
        -
          __assoc__:
            -
              - label
              - Half
            -
              - showLabel
              - ''
            -
              - value
              - half
            -
              - imageUrl
              - /assets/col-2.png
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Full
            -
              - showLabel
              - ''
            -
              - value
              - full
            -
              - imageUrl
              - /assets/col-1.png
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: supercool\buttonbox\fields\Buttons
  dd581b2f-56b7-4559-b893-329b66618f29: # Alignment
    contentColumnType: text
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: false
    settings:
      displayAsGraphic: '1'
      displayFullwidth: ''
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - showLabel
              - ''
            -
              - value
              - left
            -
              - imageUrl
              - /assets/align-left.png
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - showLabel
              - ''
            -
              - value
              - center
            -
              - imageUrl
              - /assets/align-center.png
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - showLabel
              - ''
            -
              - value
              - right
            -
              - imageUrl
              - /assets/align-right.png
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: supercool\buttonbox\fields\Buttons
  e5c502b2-96a0-40e8-906e-90865c246d78: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:d7410d44-b0f7-4f0d-8718-624e3283fd53'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d7410d44-b0f7-4f0d-8718-624e3283fd53'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
