enableVersioning: true
handle: art
name: Art
propagationMethod: all
siteSettings:
  1f4cdae2-78d7-4080-9061-8079a6f70209:
    enabledByDefault: true
    hasUrls: true
    template: detail
    uriFormat: 'detail/{slug}'
type: channel
